### ISSUE TITLE
error in youtube_refresh

### ISSUE THREAD

**Issue by tangoshot** [tangoshot/TangoShot#763]
error in youtube_refresh (when started locally).

STARTING SCRIPT: youtube_refresh
Creating records for new entries: 12122
0 ...
EXCEPTION: 
Traceback (most recent call last):
  File "applications/TangoShot/modules/ts/admin/scripts.py", line 41, in __call
    result = FN()
  File "applications/TangoShot/modules/ts/admin/scripts.py", line 112, in youtube_refresh
    response = youtube.refresh()
  File "applications/TangoShot/modules/ts/yt/youtube_refresher.py", line 147, in refresh
    incoming = self.__refresh_incoming()
  File "applications/TangoShot/modules/ts/yt/youtube_refresher.py", line 194, in __refresh_incoming
    self.refresh_items(vkeys)
  File "applications/TangoShot/modules/ts/yt/youtube_refresher.py", line 177, in refresh_items
    self.__update_item(item)
  File "applications/TangoShot/modules/ts/yt/youtube_refresher.py", line 209, in __update_item
    self.DAL.update_youtube_rec(item, vkey)
  File "applications/TangoShot/modules/ts/yt/youtube_refresher.py", line 82, in update_youtube_rec
    yt_data = self.__parse_youtube_rec(item)
  File "applications/TangoShot/modules/ts/yt/youtube_refresher.py", line 112, in __parse_youtube_rec
    likeCount = int(statistics['likeCount'])
KeyError: 'likeCount'

**Comment by tangoshot** [comment]
fixed. likeCount was missing in some videos. Google may have dropped support.
